### ISSUE TITLE
Responses posting in terminal, not into Glip

### ISSUE THREAD

**Issue by Brutalbeard** [ringcentral-ruby/lita-glip#4]
Lita application is reading responses from Glip, and responding to commands, but Lita response messages are only posting in terminal window. They aren't being posted back to the Glip group that initiated the command. 

In the below screenshots, I'm using `lita-stocks` which returns the current value of a stock symbol that the user supplies. 

<img width="763" alt="screen shot 2017-03-14 at 12 34 41 am" src="https://cloud.githubusercontent.com/assets/7102792/23886142/dd2223de-084e-11e7-9666-9683af58ebe7.png">
<img width="1123" alt="screen shot 2017-03-14 at 12 34 50 am" src="https://cloud.githubusercontent.com/assets/7102792/23886143/dd23aefc-084e-11e7-8a94-3a1992ab8a56.png">

**Comment by grokify** [comment]
That post object has `groupId` and `text` properties but not a `creatorId` property which may be causing the issue as `MessageHandler` expects that property.

I'll use [`lita-stocks`](https://rubygems.org/gems/lita-stocks) and see what's happening.

**Comment by grokify** [comment]
`lita-stocks` works for me using `lita stock rng`, `lita: stock rng` and variations. The message also has a `body.post.creatorId` property for me.

One issue could be that your robot name isn't set to match your command's robot name: "lita".

What do you have `config.robot.name` set to in the `config` block or via [`lita_dotenv`](https://github.com/grokify/lita_dotenv)?

Here's an example using the [configuration documentation](https://docs.lita.io/getting-started/configuration/):

```ruby
Lita.configure do |config|
  config.robot.name = "Lita"
end
```

and via [`lita_dotenv`](https://github.com/grokify/lita_dotenv):

`LITA_ROBOT_NAME=lita`

Here's an example: https://github.com/ringcentral-ruby/glipbot-stocks-demo

**Comment by Brutalbeard** [comment]
This is very strange still. 

I cloned your example, and added my app key and login information. Ran bundle install to make sure I had the same dependencies, and then ran 'lita' from the directory I cloned into. I received the same results. Authenticated, then all responses in the terminal window, with no body.post.creatorId. 

I'm running this directly from my mac terminal. Is there any chance this could be causing an issue? Is there a specific app permission that is needed, that I maybe didn't add?

**Comment by grokify** [comment]
I updated `lita-glip` to `v0.0.4` and included it in the demo app `Gemfile`.

Try to clone and run the example app repo again.

**Comment by Brutalbeard** [comment]
It's permissions! With the verbose error logging I got a response back saying that it was an insufficient permissions error. 

<img width="1551" alt="screen shot 2017-03-14 at 11 19 23 pm" src="https://cloud.githubusercontent.com/assets/7102792/23932175/e31b3a6e-090c-11e7-9fc7-7b0f0e41c14e.png">

**Comment by grokify** [comment]
Cool! Glad we found it!

The core change above was in `glip_sdk` `v0.0.5` which added the logging you saw.
